### PR TITLE
Upgrading PCL to newest version (for consistency).

### PR DESCRIPTION
**Pull request by Mike-E-angelo**

### CODE REVIEW

**Comment by EmptyKeys** [comment]
Do you have linux/mac to test it out with Xamarin, if they added this new PCL project support?

**Comment by Mike-E-angelo** [comment]
Ah I do not.  All I did was make this the same project type as the GameData (just copy-and-pasted it from there).  So if GameData works in Linux/Mac, then GameUILibrary should also work as well, correct?  Or is there something I am missing?

**Comment by EmptyKeys** [comment]
I'm not sure if GameData works on Linux/Mac, I didn't test it lately. I will do it later.

**Comment by EmptyKeys** [comment]
Included in latest version

**Comment by Mike-E-angelo** [comment]
Yay... great, thank you!

**Comment by EmptyKeys** [comment]
On the end I used older version, but it's unified :)

**Comment by Mike-E-angelo** [comment]
NOOOOOOOOOOOOO lol :stuck_out_tongue: 

Is that to take account for non-MonoGame frameworks?

**Comment by EmptyKeys** [comment]
MonoDevelop, but it's really not a big issue. They are pretty much the same, just diff UI in Visual Studio.

**Comment by Mike-E-angelo** [comment]
Ahhhh OK.  Gotcha.  Different world here for me, so I won't hold you back. ;)

**Pull request closed without merging**
